### ISSUE TITLE
Fairness Threshold

### ISSUE THREAD

**Issue by RCCheah** [mas-veritas2/veritastool#6]
Hi,

How do I get ratio based fairness check? For example, TPR of Group 1/TPR of Group2.
We could not find that in the API. 

In addition, we also need the threshold condition to assess ratio based fairnesss check.

Thank you.

**Comment by mas-veritas2** [comment]
The list of supported fairness metrics are as follows:
- Disparate Impact
- Demographic Parity
- Equal Opportunity
- False Positive Rate Parity
- True Negative Rate Parity
- False Negative Rate Parity
- Positive Predictive Parity
- Negative Predictive Parity
- False Discovery Rate Parity
- False Omission Rate Parity
- Equalized Odds
- Negative Equalized Odds
- Calibration by Group
- AUC Parity
- Log-loss Parity
- Mutual Information Independence
- Mutual Information Separation
- Mutual Information Sufficiency
- Root Mean Squared Error Parity
- Mean Absolute Percentage Error Parity
- Weighted Absolute Percentage Error Parity
- Harm from Rejection
- Benefit from Acquiring

We do not include TPR Ratio because what it measures is very similar to Equal Opportunity. Do you have the need to have both TPR Ratio and Equal Opportunity in practice?

For setting the threshold for all fairness metrics, you can specify the "fair_threshold" while initializing CreditScoring or CustomerMarketing object. If the value of "fair_threshold" is [0,1], it is treated as actual threshold value; if > 1, it is treated as p%-rule, e.g. fair_threshold = 80 means 80%-rule.

**Comment by RCCheah** [comment]
Hi,

In practice, we are using the ratio based metric because it is more intuitive and easier to interpret the result.

For example, any ratio outside the range of 0.8 to 1.25 (threshold) will indicate a result that is material enough for further investigation. I have attached the following URL on the topic of disparate impact for your reference. Thank you.

[https://public.dhe.ibm.com/common/ssi/ecm/47/en/47023047usen/aios-research-paper-3-bias_47023047USEN.pdf](url)

**Comment by mas-veritas2** [comment]
noted.  we will add ratio version of metrics in ver 2.0
